Implement fast quaternion implementation, minor changes to complex
mipt-npm/kmath pull request #156
Opened 2020-10-27 11:07 UTC by CommanderTvis

closes #155

2020-10-27 11:08 UTC, CommanderTvis commented
This PR currently lacks tests, also complex . quaternion operations are needed

2021-01-05 13:57 UTC, altavir reviewed
Maybe move complex and quaternion to a separate module, say `kmath-complex`? It would help to maintain proper stability guarantees. I am not sure about that, but it does not make a lot of sense to keep them in the core.

2021-01-19 12:11 UTC, altavir commented
Update plugin version to `0.7.3-1.4.30-RC` to fix tests.

2021-01-19 16:39 UTC, altavir commented
Please resolve conflicts

2021-02-08 16:53 UTC, altavir requested changes
Looks good. Only small changes are in order.

2021-02-08 16:53 UTC, altavir commented on examples/src/main/kotlin/kscience/kmath/operations/ComplexDemo.kt
> +    val result = (NDAlgebra.complex(8)) {
Revert to more readable `with` please

2021-02-08 16:53 UTC, altavir commented on kmath-complex/src/commonMain/kotlin/kscience/kmath/complex/Complex.kt
> +    public override val zero: Complex by lazy { 0.0.toComplex() }
Lazy will be much more expensive here than an assignment. I do not think that there is a difference, but probably better to keep it simple.

2021-02-08 16:53 UTC, altavir commented on kmath-core/build.gradle.kts
> +            api(project(":kmath-complex"))
Move appropriate tests to kmath-complex and remove the dependency.

2021-02-11 08:01 UTC, altavir approved these changes

2021-02-11 08:01 UTC, merged